###
GET {{url}}/demo
Accept: application/json

###
GET {{url}}/demo/one?id=5f212f630167b817a0047188
Accept: application/json

###
POST {{url}}/demo
Accept: application/json
Content-Type: application/json

{
  "name": "alalau",
  "status": "active"
}
